mission-apprentissage/tables-correspondances

.gitignore
server/src/logic/controllers/geo/geoController.js
server/src/logic/handlers/geoHandler.js

perf: getDataFromCP : spare call to apiEsSup

---

server/src/logic/controllers/geo/geoController.js

Search on insee_com & postal_code fields only

perf: improve findCode query

---

reverse_proxy/app/nginx/nginx.conf

chore: Increase request rate on nginx

---

server/src/common/model/index.js
server/src/common/mongodb.js
server/src/common/utils/esUtils.js
server/src/jobs/esIndex/esIndex.js

* Séparation schema Mongoose et schéma Mongoosastic
* Declare BCN stuff with mongo+es
* Polish createModel

Déploiement en recette

---

server/src/common/model/index.js
server/src/common/mongodb.js
server/src/common/utils/esUtils.js
server/src/jobs/esIndex/esIndex.js

* Séparation schema Mongoose et schéma Mongoosastic
* Declare BCN stuff with mongo+es
* Polish createModel

Déploiement en production

---

server/src/logic/handlers/opcoHandler.js

perf: faster findOpcosFromCfd using distinct

---

server/src/jobs/annuaire/exports.js
server/src/jobs/annuaire/referentiels/missing.js
server/src/jobs/annuaire/sources/formations.js
ui/src/pages/annuaire/EtablissementPage.js

* Add export for 'missing' referentiel
* Fix broken formations source

Mise en production

---

README.md

making a fool of semantic release bot

feat: sdk readme

---

ui/Dockerfile

Yarn build a besoin des devDependencies (ie. linter)

Fix UI Dockerfile

---

server/src/common/apis/ApiGeoAdresse.js
server/src/logic/controllers/geo/geoAdresseData.js
server/src/logic/controllers/geo/geoController.js
server/src/logic/handlers/geoHandler.js
server/src/sdk/utils/utils.ts

optional param, gives more specific result

feat(sdk): search address by cp & insee

---

server/src/common/esClient/index.js
server/src/common/model/index.js
server/src/common/mongodb.js
server/src/sdk/utils/utils.ts

```js
await initTcoModel(mongoose, { noElastic: true });
```

feat(sdk): make it possible to use sdk without eS

---

server/src/logic/controllers/bcn/Constants.js
server/src/sdk/utils/utils.ts

```js
{
'3 (CAP...)': [
'AUTRES DIPLOMES DE NIVEAU V',
'AUTRES FORMATIONS DE NIVEAU 5',
"BREVET D'ETUDES PROFESSIONNELLES",
"BREVET D'ETUDES PROFESSIONNELLES AGRICOLES",
'BREVET PROFESSIONNEL AGRICOLE DE NIVEAU V',
"CERTIFICAT D'APTITUDES PROFESSIONNELLES",
"CERTIFICAT D'APTITUDES PROFESSIONNELLES AGRICOLES",
'CERTIFICAT DE SPECIALISATION AGRICOLE DE NIVEAU 5',
"CYCLE D'INSERTION PROF.PAR ALTERNANCE",
'FCIL & FC NON DIPLOMANTE POST NIVEAU_5',
'MENTION COMPLEMENTAIRE',
"MODULE D'ACTION EN LYCEE DE NIVEAU_5",
'SES/SEGPA 3EME A 6EME ANNEE',
'TH DE NIV 5 DES CCI ET MINISTERE COMMERCE ARTISANAT PME',
'TH DE NIV 5 DES CHAMBRES DE METIERS',
"TH DE NIV 5 DES ORGANISMES ET CHAMBRES D'AGRICULTURE",
'TH DE NIV 5 EDUCATION RECTORAT GRETA ...',
'TH DE NIV 5 INSTANCES REGIONALES',
'TH DE NIV 5 …
```

feat: generate niveaux/diplomes tree from BCN

---

server/src/common/apis/ApiGeoAdresse.js
server/src/logic/controllers/geo/geoAdresseData.js
server/src/logic/controllers/geo/geoController.js
server/src/logic/handlers/geoHandler.js
server/src/logic/handlers/siretHandler.js
server/src/logic/services/etablissementService.js
server/src/sdk/utils/utils.ts

- BAN is way better with insee than with postcode
- Also fix insee code validation

feat(geoloc): Search with code insee

---

server/src/logic/controllers/geo/geoAdresseData.js
server/src/logic/controllers/geo/geoController.js
server/src/logic/handlers/geoHandler.js
server/src/sdk/utils/utils.ts

New sdk function to get address from coords.
e.g :
```js
await getAddressFromCoordinates({
latitude: 45.2344404,
longitude: 5.67547279999997,
});
```
will output :
```js
{
result: {
adresse: {
numero_voie: '3',
type_voie: 'Rue',
nom_voie: 'de la Gare',
code_postal: '38120',
code_commune_insee: '38382',
commune: 'Saint-Égrève',
num_departement: '38',
nom_departement: 'Isère',
region: 'Auvergne-Rhône-Alpes',
num_region: '84',
nom_academie: 'Grenoble',
num_academie: '8'
},
results_count: 1
},
messages: { adresse: 'Ok' }
}
```

feat: Get address data from geoloc

---

server/src/http/routes/services.js
server/src/jobs/EtablissementsUpdater/index.js
server/src/jobs/EtablissementsUpdater/updater/updater.js
server/src/logic/controllers/entrepriseController.js
server/src/logic/services/etablissementService.js

* Spare calls & errors since it is included in api entreprise response
* Also spare call to geoloc when possible since it is already done once in `getDataFromSiret` method

fix(etablissement): remove legacy call to BAN

---

server/src/common/model/schema/log.js

chore: expire logs after 7 days

---

server/src/common/model/schema/bcnLettreSpecialite.js
server/src/common/model/schema/bcnNMef.js
server/src/common/model/schema/bcnNNiveauFormationDiplome.js
server/src/common/model/schema/onisep.js
server/src/logic/controllers/bcn/BcnController.js

:zap: largement plus rapide : full training updater (sans maj des codes postaux)  en 20 minutes (sur 40K formations)

fix: faster cfd data lookup

---

docker-compose.override.yml
server/src/common/model/schema/conventionFile.js
server/src/common/model/swaggerSchema/conventionFile.js
server/src/common/utils/miscUtils.js
server/src/jobs/convetionFilesImporter/importConventionFiles.js
server/src/jobs/convetionFilesImporter/index.js
server/src/logic/controllers/conventionController.js
server/src/logic/controllers/entrepriseController.js
server/tests/unit/miscUtils-test.js
ui/Dockerfile.dev

Clean / Remove DEPP and DGEFP convention files

---

server/src/logic/controllers/bcn/BcnController.js

Ajout de la `date_ouverture` pour l'api **/cfd** des tables de correspondances

feat: add opening date to cfd api

---

server/src/logic/controllers/rncp/rncpController.js
server/src/logic/handlers/cfdHandler.js

Modification du cfdHandler et du rncpController pour pouvoir retrouver une liste de RNCPs à partir d'un code CFD.

fix(server) : handle multiple RNCPs for one CFD
